// <auto-generated/>
#nullable enable
using System;
using Microsoft.CodeAnalysis;

namespace ZCrew.Extensions.DependencyInjection.Registration;

/// <summary>
///     Registers the <c>[Service]</c> implementation against an additional service type, optionally under a key. Repeat
///     it to add several service types; the implementation and every added service type resolve to a single shared
///     instance (for singleton and scoped lifetimes).
/// </summary>
/// <remarks>
///     The implementation must be assignable to the service type.
/// </remarks>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = true, Inherited = false)]
[Embedded]
internal class AsAttribute : Attribute
{
    /// <summary>
    ///     Registers the implementation against <paramref name="serviceType"/>, optionally under <paramref name="key"/>.
    /// </summary>
    /// <param name="serviceType">The service type to register the implementation against.</param>
    /// <param name="key">The optional service key; when omitted the service type is registered unkeyed.</param>
    public AsAttribute(Type serviceType, object? key = null)
    {
        ServiceType = serviceType;
        Key = key;
    }

    /// <summary>
    ///     The service type the implementation is registered against.
    /// </summary>
    public Type ServiceType { get; }

    /// <summary>
    ///     The optional service key for this service type.
    /// </summary>
    public object? Key { get; }
}

/// <summary>
///     Registers the <c>[Service]</c> implementation against the service type <typeparamref name="T"/>, optionally
///     under a key. The generic form of <see cref="AsAttribute"/>; use the non-generic form for open generics.
/// </summary>
/// <typeparam name="T">The service type to register the implementation against.</typeparam>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = true, Inherited = false)]
internal sealed class AsAttribute<T> : AsAttribute
{
    /// <summary>
    ///     Registers the implementation against <typeparamref name="T"/>, optionally under <paramref name="key"/>.
    /// </summary>
    /// <param name="key">The optional service key; when omitted the service type is registered unkeyed.</param>
    public AsAttribute(object? key = null)
        : base(typeof(T), key) { }
}
