// <auto-generated/>
#nullable enable
using System;
using Microsoft.CodeAnalysis;

namespace ZCrew.Extensions.DependencyInjection.Registration;

/// <summary>
///     Keys the <c>[Service]</c> implementation's own registration. Service types added with <c>[As]</c> can choose to
///     specify their own keys independently.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
[Embedded]
internal sealed class KeyedAttribute : Attribute
{
    /// <summary>
    ///     Keys the implementation's registration under <paramref name="key"/>.
    /// </summary>
    /// <param name="key">The service key.</param>
    public KeyedAttribute(object key)
    {
        Key = key;
    }

    /// <summary>
    ///     The service key applied to the implementation's registration.
    /// </summary>
    public object Key { get; }
}
