// <auto-generated/>
#nullable enable
using System;
using Microsoft.CodeAnalysis;

namespace ZCrew.Extensions.DependencyInjection.Registration;

/// <summary>
///     Marks a type as a service to register. The type is collected by the source generator and registered with
///     <c>Services.FromThisAssembly()</c>. On its own it registers the implementation against itself as a singleton.
///     Combine it with the modifier attributes to add service types (<c>[As&lt;T&gt;]</c>), a lifetime
///     (<c>[Singleton]</c>, <c>[Scoped]</c>, <c>[Transient]</c>), or a key for the implementation (<c>[Keyed]</c>).
///     Bracket grouping is cosmetic: <c>[Service, Scoped]</c> and <c>[Service][Scoped]</c> are identical.
/// </summary>
/// <example>
///     <code>
///     [Service]                                             // singleton, registered as Clock
///     public class Clock;
///
///     [Service, Scoped]
///     [As&lt;IHealthCheck&gt;("Database"), As&lt;IDatabaseHealthCheck&gt;]  // one shared scoped instance
///     public class DatabaseHealthCheck : IHealthCheck, IDatabaseHealthCheck;
///     </code>
/// </example>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
[Embedded]
internal sealed class ServiceAttribute : Attribute;
