// <auto-generated/>
#nullable enable
using System;
using Microsoft.CodeAnalysis;

namespace ZCrew.Extensions.DependencyInjection.Registration;

/// <summary>
///     Registers the <c>[Service]</c> implementation with the singleton lifetime. This is the default, so the attribute
///     is only needed for emphasis.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
[Embedded]
internal sealed class SingletonAttribute : Attribute;
