// <auto-generated/>
#nullable enable
using System;
using Microsoft.CodeAnalysis;

namespace ZCrew.Extensions.DependencyInjection.Registration;

/// <summary>
///     Registers the <c>[Service]</c> implementation with the transient lifetime. Each service type is registered
///     directly against the implementation (no shared instance).
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
[Embedded]
internal sealed class TransientAttribute : Attribute;
