<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <!-- Source generator -->
    <PackageVersion Include="Polyfill" Version="11.4.1" />
    <PackageVersion Include="ZCrew.Extensions.CodeAnalysis.CSharp" Version="1.0.0-preview.9" />
    <PackageVersion Include="ZCrew.Extensions.CodeAnalysis.CSharp.Testing" Version="1.0.0-preview.9" />
    <!-- Benchmarking -->
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="Castle.Windsor" Version="6.0.0" />
    <PackageVersion Include="Scrutor" Version="7.0.0" />
  </ItemGroup>
</Project>