// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace ZCrew.Extensions.DependencyInjection.Registration;

[global::Microsoft.CodeAnalysis.Embedded]
internal static class Services
{
    public static global::ZCrew.Extensions.DependencyInjection.Registration.ServiceFilter FromThisAssembly()
    {
        return new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceFilter(new global::ZCrew.Extensions.DependencyInjection.Registration.Service[]
        {
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.EnumKeyed), new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceAttribute(new global::System.Type[] { typeof(global::Sample.IBar) }) { Key = global::Sample.Region.West }),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.FooService), new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceAttribute(new global::System.Type[] { typeof(global::Sample.IFoo) })),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.LongKeyed), new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceAttribute(new global::System.Type[] { typeof(global::Sample.IBar) }) { Key = (long)5 }),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.MultiAttr), new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceAttribute(new global::System.Type[] { typeof(global::Sample.IBar) }) { Key = "second" }),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.MultiAttr), new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceAttribute(new global::System.Type[] { typeof(global::Sample.IFoo) })),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.MultiShared), new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceAttribute(new global::System.Type[] { typeof(global::Sample.IFoo), typeof(global::Sample.IBar) })),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.OpenGeneric<>), new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceAttribute(new global::System.Type[] { typeof(global::Sample.IFoo) })),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.Outer.Nested), new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceAttribute(new global::System.Type[] {  })),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.PlainService), new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceAttribute(new global::System.Type[] {  })),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.ScopedFoo), new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceAttribute(new global::System.Type[] { typeof(global::Sample.IFoo) }) { Lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped }),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.StringKeyed), new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceAttribute(new global::System.Type[] { typeof(global::Sample.IBar) }) { Key = "primary" }),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.StructService), new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceAttribute(new global::System.Type[] {  })),
        });
    }
}