// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace ZCrew.Extensions.DependencyInjection.Registration;

[global::Microsoft.CodeAnalysis.Embedded]
internal static class Services
{
    public static global::ZCrew.Extensions.DependencyInjection.Registration.ServiceFilter FromThisAssembly()
    {
        return new global::ZCrew.Extensions.DependencyInjection.Registration.ServiceFilter(new global::ZCrew.Extensions.DependencyInjection.Registration.Service[]
        {
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.EnumKeyed), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton, global::Sample.Region.West),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.FooService), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton, null, (typeof(global::Sample.IFoo), null)),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.LongKeyed), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton, (long)5),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.MixedKeyed), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton, null, (typeof(global::Sample.IFoo), "Database"), (typeof(global::Sample.IBar), null)),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.MultiKeyed), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton, null, (typeof(global::Sample.IBar), "smtp"), (typeof(global::Sample.IBar), "ses")),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.MultiShared), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton, null, (typeof(global::Sample.IFoo), null), (typeof(global::Sample.IBar), null)),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.OpenGeneric<>), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton, null, (typeof(global::Sample.IRepository<>), null)),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.Outer.Nested), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton, null),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.PlainService), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton, null),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.ScopedFoo), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped, null, (typeof(global::Sample.IFoo), null)),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.StringKeyed), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton, "primary"),
            global::ZCrew.Extensions.DependencyInjection.Registration.Service.From(typeof(global::Sample.StructService), global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton, null),
        });
    }
}