using System.Collections.Immutable;
using ZCrew.Extensions.CodeAnalysis.CSharp.Text;
using ZCrew.Extensions.DependencyInjection.Generator.Models;
using ZCrew.Extensions.DependencyInjection.Generator.Registration;

namespace ZCrew.Extensions.DependencyInjection.Generator.Emitters;

/// <summary>
///     Emits one attributed-registration scan file: an <c>[Embedded] internal static</c> entry point whose
///     <c>FromThisAssembly()</c> returns a <c>ServiceFilter</c> wrapping the hard-coded <c>Service[]</c>, one
///     <c>Service.From(typeof(impl), attribute)</c> element per attribute usage. Items are flattened to one element per
///     attribute and ordered so the output is stable across runs.
/// </summary>
internal static class RegistrationEmitter
{
    public static string Emit(RegistrationEmitConfig config, ImmutableArray<RegistrationScanInfo> items)
    {
        var entries = new List<(string Implementation, string Construction)>();
        foreach (var item in items)
        {
            foreach (var construction in item.AttributeConstructions)
            {
                entries.Add((item.ImplementationTypeof, construction));
            }
        }

        entries.Sort(
            static (left, right) =>
            {
                var byImplementation = string.CompareOrdinal(left.Implementation, right.Implementation);
                return byImplementation != 0
                    ? byImplementation
                    : string.CompareOrdinal(left.Construction, right.Construction);
            }
        );

        var source = new FormattedStringBuilder();
        source
            .AppendAutoGeneratedComment()
            .AppendNullableEnable()
            .AppendCommonPragmaDisable()
            .AppendLine()
            .AppendFileScopedNamespaceDeclaration(config.Namespace)
            .AppendLine();

        EmitEntryPoint(source, config, entries);

        return source.ToString();
    }

    private static void EmitEntryPoint(
        FormattedStringBuilder source,
        RegistrationEmitConfig config,
        List<(string Implementation, string Construction)> entries
    )
    {
        source
            .AppendEmbeddedAttribute()
            .Append("internal static class ")
            .Append(config.EntryPointClassName)
            .AppendLine()
            .AppendBlock(body =>
                body.Append("public static ")
                    .Append(config.ServiceFilterTypeFullName)
                    .Append(" FromThisAssembly()")
                    .AppendLine()
                    .AppendBlock(method => EmitReturn(method, config, entries))
            );
    }

    private static void EmitReturn(
        FormattedStringBuilder method,
        RegistrationEmitConfig config,
        List<(string Implementation, string Construction)> entries
    )
    {
        method
            .Append("return new ")
            .Append(config.ServiceFilterTypeFullName)
            .Append("(new ")
            .Append(config.ServiceTypeFullName)
            .Append("[]")
            .AppendLine()
            .AppendBlock(array =>
            {
                foreach (var entry in entries)
                {
                    array
                        .Append(config.ServiceTypeFullName)
                        .Append(".From(typeof(")
                        .Append(entry.Implementation)
                        .Append("), ")
                        .Append(entry.Construction)
                        .Append("),")
                        .AppendLine();
                }
            })
            .Append(");");
    }
}
