<Project>
  <!-- This makes sure the outer Directory.Build.props file in the root of the solution is read and applied -->
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"/>

  <!-- Common properties for all library projects -->
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <WarningsAsErrors>$(WarningsAsErrors);IL2026;IL2067;IL2070;IL2072;IL2075;IL2077;IL2111;IL3050</WarningsAsErrors>
  </PropertyGroup>

  <!-- Common projects for all library projects -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <!-- Common NuGet package metadata -->
  <PropertyGroup>
    <Authors>Matt Zawislak</Authors>
    <Company>ZCrew</Company>
    <PackageProjectUrl>https://github.com/ZCrewSoftware/ZCrew.Extensions.DependencyInjection</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ZCrewSoftware/ZCrew.Extensions.DependencyInjection.git</RepositoryUrl>
    <DebugType>embedded</DebugType>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>icon.png</PackageIcon>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <!-- Make internals visible to the corresponding test project(s) -->
  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).UnitTests" />
    <InternalsVisibleTo Include="$(AssemblyName).IntegrationTests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
</Project>
